name: generate-rss

on:
  schedule:
    - cron: "0 * * * *"   # runs every 30 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: |
          npm install playwright

      - name: Run RSS generator
        run: node generate-rss.js

      - name: Commit & Push feed.xml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add feed.xml
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update feed.xml"
            git push
          fi